services:
  - type: web
    name: lms-backend
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/springapp-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 10000
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-vercel-app.vercel.app